import '@/app/globals.scss'
import { Providers } from '@/shared/config'
import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'

const roboto_condensed = Roboto_Condensed({
	weight: ['400', '500', '600', '700', '900'],
	subsets: ['cyrillic', 'latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={roboto_condensed.className}>
				<Providers>
					<div className='bg-background'>{children}</div>
				</Providers>
			</body>
		</html>
	)
}
