name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run remote command via SSH
      uses: D3rHase/ssh-command-action@latest
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user: ${{ secrets.USER }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
        command: echo 'Hello, World!!'
